feat: add committee to centralized br
witnet/witnet-ethereum-block-relay pull request #27
Opened 2020-12-02 17:29 UTC by clbartoli

The Centralized block relay should have a committee defined when deployed, so that not only onne address can post blocks

2020-12-04 14:33 UTC, girazoki commented on contracts/CentralizedBlockRelay.sol
> +  }
FMT

2020-12-10 09:27 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
>      witnet = msg.sender;
Maybe it is not required anymore! :)

2020-12-10 09:28 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
> +
fmt (too many new lines) :rofl:

2020-12-10 09:28 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
> +
```suggestion
```

2020-12-10 09:37 UTC, mariocao requested changes
And you metioned to me, include the `isAuthorized` modifier to the `isUpgradeable` . :P

2020-12-10 09:37 UTC, mariocao commented on test/cent_block_relay.js
> +      blockRelayInstance = await CentralizedBlockRelay.new(committee, {
I would also test the other committee member :)

2020-12-10 09:37 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
> +        return false;
indentation?

2020-12-10 09:37 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
> +
Maybe this function should be inside the modifier `isAuthorized`

2020-12-11 08:48 UTC, girazoki approved these changes

2020-12-11 09:11 UTC, mariocao commented on contracts/CentralizedBlockRelay.sol
> +  event Prueba(uint256 _id);
You forgot to remove it :)

2020-12-11 09:30 UTC, mariocao approved these changes

2020-12-11 09:31 UTC, merged